# Generated by Django 6.0.2 on 2026-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderroom',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderroom',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderroom',
            name='room_password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
